### ISSUE TITLE
TODO: wrapup before conference

### ISSUE THREAD

**Issue by simonkassel** [azavea/foss4g-2022-hitl-groundwork-rastervision#25]
**Presentation:**
- [x] Update video to include better example of initial predictions @simonkassel 
- [x] Update results section with better, more targeted example @simonkassel 
- [x] Record Adeel's portion of the presentation @AdeelH 
- [x] Include more talk of open-source components in the RV and GW overview slides @aaronxsu @AdeelH @simonkassel 
- [x] Clarify that "HITL" refers to "human-in-the-loop" @simonkassel 
- [x] Discuss ways that attendees can get setup for hitl @aaronxsu 

**Conference logistics:**
- [x] Ask the organizers to urgently fix the bug on their site that's causing our talk to not show up in the schedule @simonkassel 
- [x] Check in with conference about audio situation when adeel's video plays @simonkassel 
- [ ] Export slides as `.ppt` and put on thumb drive @simonkassel @AdeelH 

**Development**
- [x] Update HITL feature flag frontend check @aaronxsu (PR up: https://github.com/raster-foundry/groundwork/pull/1898)
- [ ] #23 @simonkassel 
- [ ] #26 @aaronxsu 
- [x] #24 @AdeelH 
- [x] Update Terraform env vars for production @aaronxsu 
- [x] Release Raster Foundry to get HITL backend support out @aaronxsu 
- [x] Release GroundWork @aaronxsu 
- [x] Mark Adeel, Simon, Aaron's accounts as HITL enabled on production Auth0 tenant @aaronxsu

**Comment by aaronxsu** [comment]
Hey @simonkassel , as discussed in a call, I'd recommend prioritizing the tasks related to the presentation.

Regarding the two enhancement issues 23 and 26, I'd suggest we divide the work up. Which one do you pick or have started? I will work on the other one.
